### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by shujaatak** [aklomp/osymandias#1]
osymandias is a great project and it deserves to be cross platform!
As it uses GTK so it's possible to build it on Windows but I see that it uses pthreads instead of C++11 threads so it's hard to build on Windows. 
Also it would be great if a brief summary is included in the readme file about how to build it.

**Comment by aklomp** [comment]
Hey, thanks for your interest in Osymandias.

This project is still in a very raw, unfinished, pre-alpha state and is not intended to be used by end users. I'm not supporting it yet, and perhaps never will. Right now it's just a hobby project of mine that I play around with in my free time.

There are no build instructions in the `README` because the project is not even officially in a buildable state. You are of course welcome to look at the `Makefile` and try to build it for yourself, but you are on your own. I offer no guarantees at all on the fitness of the code for any purpose.

I agree that a cross-platform build would be cool, but it's simply not a concern at this time. The focus now is on getting the program fundamentals done. When those are in place, I _might_ consider a Windows port, and move the build system to Clang and use MinGW as the cross compiler. I won't be using C++11 threads because this program is written entirely in C11.

As stated in the `README` file, I one day plan to properly release and package this program, but that day is still a while in the future.
